config/routes.rb
Rails.application.routes.draw do
  resources :portfolios
  resources :stocks
  resources :users

  root 'sessions#home'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'

  delete '/signout', to: 'sessions#destroy'

  post '/sessions/create', to: 'sessions#create'

  get '/stocks', to: 'stocks#index'

  get '/search', to: 'stocks#search'


  get '/portfolio', to: 'portfolio#index'

  # Maybe need to build a scaffold for transactions?





  # Note to self:
  # I am going through the rails guide and datapond and copying and pasting what makes
  # sense as I forgot how this works

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/portfolio.rb
# Might not need this connection. 
# Might just be good with doing a stocks scope. 
# We shall seeeee

class Portfolio < ApplicationRecord
    belongs_to :user 
    has_many :stocks
end

app/models/session.rb
class Session < ApplicationRecord
end

app/models/stock.rb
class Stock < ApplicationRecord
    belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
    # If I'm having problems with the password: 
    # has_secure_password validations: false
    has_secure_password
    validates :password, presence: true, length: { minimum: 4 }
    has_many :stocks

    validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        User.find_by(id: session[:user_id])  
        # @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        !!current_user
    end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]


  def index
    @portfolios = Portfolio.all

    @stocks = Stock.all
    @portfolio = {}
    @portfolio_value = {}

    @stocks.each { |i|
      if @portfolio.include?(i.ticker) 
        @portfolio[i.ticker] += i.shares
      else 
        @portfolio[i.ticker] = i.shares
      end 
    } 
    # Ideally would create an API call here grabbing all the current 
    # values of the porfolio
      # Ex: IBM's current value (from API) * number of shares = IBM's value 
      # Do the above for all stocks in portfolio
      # Present the total value of portfolio
  end


  private
    def portfolio_params
      params.require(:portfolio).permit(:user_id, :ticker, :price, :shares)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  helper_method :current_user 

  def new
    @user = User.new
  end

  def sign_in
  end 

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
       sessions[:user_id] = @user.id
       redirect_to '/'
    else
       redirect_to '/signin'
       flash[:alert] = "Sorry, please try to sign up."
    end
  end

  def destroy
    log_out
    redirect_to '/'
  end

  def log_out
    reset_session
    @current_user = nil
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  helper_method :current_user 

  def index
    @user = current_user
    @stocks = Stock.all
    @stocks_sum = 0;

    @stocks.each do |stock|
      if stock.price
        @stocks_sum = @stocks_sum + stock.price
      end  
    end 
  end 

  def new
    @stock = Stock.new
  end

  def create
    @stock = Stock.new(stock_params)
    @stocks = Stock.all
    @stock.user_id = current_user.id

    # Setup authorization for API call
    @api_call = Intrinio.configure do |config|
        config.api_key['api_key'] = 'OjUyOGY1MjM0ZmE1OGYzM2I1ZDY2MjA0OWNiOGQ5Zjc5'
      end
      security_api = Intrinio::SecurityApi.new
      identifier = "#{@stock.ticker}" # String | A Security identifier (Ticker, FIGI, ISIN, CUSIP, Intrinio ID)
      opts = { 
        source: nil
      }
      begin
        result = security_api.get_security_realtime_price(identifier, opts)
        puts result
        @stock.price = @stock.shares * (result.last_price);
      rescue Intrinio::ApiError => e
        puts "Exception when calling SecurityApi->get_security_stock_prices: #{e}"
      end

    if @stock.save
      redirect_to stocks_path(@stock)
    else 
      render :new 
    end 

    # Can't buy anymore stock if spent more than $5000
      # Idea is to disable the submit button if slightly in debt 
    # @stocks_sum = 0;
    # @can_i_buy = false;

    # @stocks.each do |stock|
    #   if stock.price
    #     @stocks_sum = @stocks_sum + stock.price
    #   end  
    # end 

    # if @stocks_sum < 0 
    #   @can_i_buy = false
    # end 
  end 


  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end 
  end

  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def stock_params
      params.require(:stock).permit(:user_id, :ticker, :shares, :price)
    end

end 


  

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    redirect_to stocks_path 
  end

  def index 
    @current_user = User.find_by_id(session[:user_id])
  end 

  def create
    @user = User.create(params.require(:user).permit(:email,        
    :password))
    session[:user_id] = @user.id
    redirect_to '/'
    @user = User.new(user_params)
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :uid)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.4.1.js"  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="  crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>


    <title>Stockifier</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="navbar navbar-default bg-light">
    <div class="nav-item">

      <% if current_user %>
        <button class="btn btn-sm btn-outline-secondary" type="button">
        <%= link_to "Sign out", signout_path, method: :delete %></button>
      </div>

      <div class="nav-item">
        <%= link_to "Home", "/" %>
      </div>

      <div class="nav-item">
        <%= link_to "Buy Stocks/ Transactions", stocks_path %>
      </div>

      <div class="nav-item">
        <%= link_to "Portfolio", portfolios_path %>
      </div>
      
        <% else %>
      <h3>
      <%= button_to "Sign In", '/signin', method: :get%>
      <%= button_to "Sign Up", '/users/new', method: :get%>
      </h3>

    <% end %>
    </div>

    <div id = "app-container">
        <%= yield %>
    </div>

  </div>

  </body>
</html>

app/views/portfolios/Extra stuff/_form.html.erb
<%= form_with(model: portfolio, local: true) do |form| %>
  <% if portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
      <% portfolio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :ticker %>
    <%= form.text_field :ticker %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :shares %>
    <%= form.number_field :shares %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/Extra stuff/edit.html.erb
<h1>Editing Portfolio</h1>

<%= render 'form', portfolio: @portfolio %>

<%= link_to 'Show', @portfolio %> |
<%= link_to 'Back', portfolios_path %>

app/views/portfolios/Extra stuff/new.html.erb
<h1>New Portfolio</h1>

<%= render 'form', portfolio: @portfolio %>

<%= link_to 'Back', portfolios_path %>

app/views/portfolios/Extra stuff/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @portfolio.user_id %>
</p>

<p>
  <strong>Ticker:</strong>
  <%= @portfolio.ticker %>
</p>

<p>
  <strong>Price:</strong>
  <%= @portfolio.price %>
</p>

<p>
  <strong>Shares:</strong>
  <%= @portfolio.shares %>
</p>

<%= link_to 'Edit', edit_portfolio_path(@portfolio) %> |
<%= link_to 'Back', portfolios_path %>

app/views/portfolios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Your Portfolio</h1>
<br/>
<table>
  <thead>
    <tr>
      <th>Ticker</th>
      <th>Shares</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @portfolio.each do |ticker| %>
      <tr>
        <td><%= ticker[0] %></td>
        <td><%= ticker[1] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/stocks/_form.html.erb
<h4>
<%=form_for @stock do |f|%>

    <div class="col-lg-12 mt-5">
      <% if flash[:alert] %>
        <div class="alert alert-warning"><%= flash[:alert] %></div>
      <% end %>
    <div class="mx-auto mt-5" style="width: 400px">

    <% if stock.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

        <ul>
        <% stock.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.label :ticker, "Ticker: " %>
    <%= f.select :ticker, ['MMM', 'AXP', 'AAPL', 'BA', 'CAT', 'CVX', 'CSCO', 'KO', 'DIS', 'DOW', 'XOM', 'GS', 'HD', 'IBM', 'INTC', 'JNJ', 'JPM', 'MCD', 'MRK', 'MSFT', 'NKE', 'PFE', 'PG', 'TRV', 'UTX', 'UNH', 'VZ', 'V', 'WMT', 'WBA']%>

    <br/>

    <%= f.label :shares, "Shares: " %>
    <%= f.number_field :shares %>
    <br>
    
    <%= f.submit "Buy the stock" %> 

<% end %>
</h4>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<p id="notice"><%= notice %></p>

<% if !@user %>
Welcome to Stockifier! <br/>
Please sign up or sign in. <br/><br/>

Here you have $5000 to invest in whichever DOW 30 stocks you would like.<br/>
You can see your portfolio, with fun colors depending on how the stock is doing, and all the transcations you've made. 

<% end %>


<% if @user %>
  <br/>
  <h2><%= link_to 'Buy Stocks', new_stock_path %></h2>
  <br/>
  <h3>You have $<%= 5000 - @stocks_sum %> left to invest</h3>
  <h5>I am using an API sandbox, so we have access to the DOW 30 stocks data only. <br/></h5>
<br/>
<br/>
  <h2>Transactions:</h2>

    <table>
      <thead>
        <tr>
          <th>User</th>
          <th>Ticker</th>
          <th>Shares</th>
          <th>Price</th>
          <th colspan="4"></th>
        </tr>
      </thead>
      <tbody>
        <% @stocks.each do |stock| %>
          <tr>
            <td><%= stock.user_id %></td>
            <td><%= stock.ticker %></td>
            <td><%= stock.shares %></td>
            <td><%= stock.price %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  <br>
<% end %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/search.html.erb
<h4>Stock info
  <% @alpha_ticker%> </h4>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @stock.user_id %>
</p>

<p>
  <strong>Ticker:</strong>
  <%= @stock.ticker %>
</p>

<p>
  <strong>Shares:</strong>
  <%= @stock.shares %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>